@TaskGX_HostAddress = http://localhost:5192

GET {{TaskGX_HostAddress}}/
Accept: application/json

###

POST {{TaskGX_HostAddress}}/api/autenticacao/login
Content-Type: application/json

{
  "email": "utilizador@taskgx.com",
  "senha": "Senha123!"
}

###
